project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - datasets.qmd
    - assignments.qmd
    - assignment1.qmd
    - assignment2.qmd
    - assignment3.qmd
    - assignment4.qmd
    - assignment5.qmd
    - assignment6.qmd
           
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: BUSI 520
    file: index.qmd
    right:
      
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd
      - text: Notebooks
        href: https://github.com/kerryback/busi520/tree/main/notebooks
      - text: Datasets 
        file: datasets.qmd
        
format: 
  html:
    theme: yeti
    scss: styles.css
    
   



